language: python
python:
  - "2.7"
sudo: false
cache:
  directories:
    - "~/.platformio"
install:
  - pip install -U platformio
  - platformio update
script:
  - platformio run
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: ".pio/build/sanguino1284p/firmware.hex"
  skip_cleanup: true
  on:
    tags: true
